#!/bin/bash

# Check the destribution and save it as a variable (Debian, Mac, ...)
if [ -f /etc/os-release ]; then
  . /etc/os-release
  OS=$NAME
elif type lsb_release >/dev/null 2>&1; then
  OS=$(lsb_release -si)
elif [ -f /etc/lsb-release ]; then
  . /etc/lsb-release
  OS=$DISTRIB_ID
elif [ -f /etc/debian_version ]; then
  OS=Debian
elif [ -f /etc/SuSe-release ]; then
  OS=SuSE
elif [ -f /etc/redhat-release ]; then
  OS=RedHat
else
  OS=$(uname -s)
fi

# Check if this directory is located in $HOME/.dotfiles
if [ ! -d "$HOME/.dotfiles" ]; then
  echo "Please clone this repository to $HOME/.dotfiles"
  exit 1
fi

# Run install script for git
source $HOME/.dotfiles/Git/install

# Run install script for zsh
source $HOME/.dotfiles/zsh/install

# Run install script for tmux
source $HOME/.dotfiles/tmux/install

# .hushlogin
touch $HOME/.hushlogin