#!/bin/bash

# Check if this directory is located in $HOME/.dotfiles
if [ ! -d "$HOME/.dotfiles" ]; then
  echo "Please clone this repository to $HOME/.dotfiles"
  exit 1
fi

# Run install script for git
source $HOME/.dotfiles/Git/install

# Run install script for zsh
source $HOME/.dotfiles/zsh/install

# Run install script for tmux
source $HOME/.dotfiles/tmux/install
