execute pathogen#infect()
syntax on
filetype plugin indent on

set ttymouse=xterm2
set mouse=a
" set cursorline
set enc=utf-8
set fillchars=vert:\│ 

" Undofile setup
if !isdirectory($HOME."/.vim")
    call mkdir($HOME."/.vim", "", 0770)
endif
if !isdirectory($HOME."/.vim/undo-dir")
    call mkdir($HOME."/.vim/undo-dir", "", 0700)
endif
set undodir=~/.vim/undo-dir
set undofile

" let g:coqtail_auto_set_proof_diffs = 'on'

let g:zenburn_high_Contrast=1
let g:solarized_termcolors=256
let my_colorschemes = ['dracula', 'zenburn', 'solarized']
let random_colorscheme = my_colorschemes[rand() % (len(my_colorschemes))]
if random_colorscheme == 'solarized'
	if (rand() % 2 == 0)
		set background=dark
	else
		set background=light
	endif
else
	set background=dark
endif



if &background ==# 'dark'
	augroup CoqtailHighlights
	autocmd!
	autocmd ColorScheme *
		\  hi def CoqtailChecked ctermbg=237
    		\| hi def CoqtailSent    ctermbg=60
	augroup END
else
	augroup CoqtailHighlights
		autocmd!
		autocmd ColorScheme *
					\  hi def CoqtailChecked ctermbg=252
					\| hi def CoqtailSent ctermbg=146
	augroup END
endif

execute 'colorscheme' random_colorscheme

let g:unicode_map = {
  \ "\\fun"     :   "λ",
  \ "\\mult"    :   "⋅",
  \ "\\ent"     :   "⊢",
  \ "\\valid"   :   "✓",
  \ "\\diamond" :   "◇",
  \ "\\box"     :   "□",
  \ "\\bbox"   	:   "■",
  \ "\\later"  	:   "▷",
  \ "\\pred"   	:   "φ",
  \ "\\and"    	:   "∧",
  \ "\\or"     	:   "∨",
  \ "\\comp"   	:   "∘",
  \ "\\ccomp"  	:   "◎",
  \ "\\all"    	:   "∀",
  \ "\\ex"     	:   "∃",
  \ "\\to"     	:   "→",
  \ "\\sep"    	:   "∗",
  \ "\\lc"     	:   "⌜",
  \ "\\rc"     	:   "⌝",
  \ "\\Lc"     	:   "⎡",
  \ "\\Rc"     	:   "⎤",
  \ "\\lam"    	:   "λ",
  \ "\\empty"  	:   "∅",
  \ "\\Lam"    	:   "Λ",
  \ "\\Sig"    	:   "Σ",
  \ "\\-"      	:   "∖",
  \ "\\aa"     	:   "●",
  \ "\\af"     	:   "◯",
  \ "\\auth"   	:   "●",
  \ "\\frag"   	:   "◯",
  \ "\\iff"    	:   "↔",
  \ "\\gname"  	:   "γ",
  \ "\\incl"   	:   "≼",
  \ "\\latert" 	:   "▶",
  \ "\\update" 	:   "⇝",
  \ "\\\"o"     :   "ö",
  \ "_a"        :   "ₐ",
  \ "_e"        :   "ₑ",
  \ "_h"        :   "ₕ",
  \ "_i"        :   "ᵢ",
  \ "_k"        :   "ₖ",
  \ "_l"        :   "ₗ",
  \ "_m"        :   "ₘ",
  \ "_n"        :   "ₙ",
  \ "_o"        :   "ₒ",
  \ "_p"        :   "ₚ",
  \ "_r"        :   "ᵣ",
  \ "_s"        :   "ₛ",
  \ "_t"        :   "ₜ",
  \ "_u"        :   "ᵤ",
  \ "_v"        :   "ᵥ",
  \ "_x"        :   "ₓ",
\ }

