#!/bin/bash

# Check if zsh installed
if [ -z "$(command -v zsh)" ]; then
  echo "Please install zsh first"
  exit 1
fi

# Check if default shell is zsh
if [[ ! "$SHELL" =~ .*zsh$ ]]; then
  echo "Please set zsh as your default shell - chsh -s $(which zsh)"
  exit 1
fi

git clone 'https://github.com/hyperupcall/autoenv' ~/.autoenv
printf '%s\n' "source ~/.autoenv/activate.sh" >> "${ZDOTDIR:-$HOME}/.zprofile"

# Check if .zshrc exists
if [ -f "$HOME/.zshrc" ]; then
  echo "You already have .zshrc file."
  # Ask if user wants to replace it
  read -p "Do you want to replace it? [y/n] " -n 1 -r REPLY
  echo
  if [[ $REPLY =~ ^[Yy]$ ]]; then
    echo "Replacing .zshrc file..."
    ln -sf $HOME/.dotfiles/zsh/.zshrc $HOME/.zshrc
  fi
else
  echo "Installing .zshrc file..."
  ln -s $HOME/.dotfiles/zsh/.zshrc $HOME/.zshrc
fi

# Check if .zshenv exists
if [ -f "$HOME/.zshenv" ]; then
  echo "You already have .zshenv file."
  # Ask if user wants to replace it
  read -p "Do you want to replace it? [y/n] " -n 1 -r REPLY
  echo
  if [[ $REPLY =~ ^[Yy]$ ]]; then
    echo "Replacing .zshenv file..."
    ln -sf $HOME/.dotfiles/zsh/.zshenv $HOME/.zshenv
  fi
else
  echo "Installing .zshenv file..."
  ln -s $HOME/.dotfiles/zsh/.zshenv $HOME/.zshenv
fi
