# Path to your oh-my-zsh installation.
export ZSH="$HOME/.oh-my-zsh"

export DOTFILES="$HOME/.dotfiles"

export THEME_PATH="$DOTFILES/zsh-dracula-theme"

if [ ! -d "$THEME_PATH" ] ; then
  git clone https://github.com/dracula/zsh.git "$THEME_PATH"
  ln -s "$THEME_PATH/dracula.zsh-theme" "$ZSH/themes/dracula.zsh-theme"
fi

ZSH_THEME="dracula"


# Which plugins would you like to load?
# Standard plugins can be found in ~/.oh-my-zsh/plugins/*
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
plugins=(git)

source $ZSH/oh-my-zsh.sh

if [ $(command -v opam | wc -l) -gt 0 ] ; then
  eval `opam config env`
fi
